-- AURA BIOBANK PORTAL: POSTGRESQL SCHEMA INITIALIZATION

-- 1. Labs Table
CREATE TABLE IF NOT EXISTS labs (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL UNIQUE,
  location_address TEXT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Roles Table
CREATE TABLE IF NOT EXISTS roles (
  role_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  role_name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT
);

-- 3. Permissions Table
CREATE TABLE IF NOT EXISTS permissions (
  permission_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  permission_name VARCHAR(255) NOT NULL UNIQUE,
  module_name VARCHAR(255) NOT NULL
);

-- 4. Role Permissions Table
CREATE TABLE IF NOT EXISTS role_permissions (
  role_permission_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  role_id INTEGER NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
  permission_id INTEGER NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE
);

-- 5. Locations Table
CREATE TABLE IF NOT EXISTS locations (
  location_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  lab_id INTEGER REFERENCES labs(id) ON DELETE CASCADE,
  location_name VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Active'
);

-- 6. Users Table
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  full_name VARCHAR(255),
  phone_number VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  employee_id VARCHAR(100),
  designation VARCHAR(100),
  role_id INTEGER REFERENCES roles(role_id) ON DELETE SET NULL,
  lab_id INTEGER REFERENCES labs(id) ON DELETE SET NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Active',
  password VARCHAR(255),
  password_plain VARCHAR(255), -- Short-term compatibility / migration aid for Biobank Portal login
  created_by VARCHAR(255),
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_by VARCHAR(255),
  modified_date VARCHAR(255),
  activated_by VARCHAR(255),
  activated_date VARCHAR(255),
  deactivated_by VARCHAR(255),
  deactivated_date VARCHAR(255),
  suspended_by VARCHAR(255),
  suspended_date VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. User Locations Table
CREATE TABLE IF NOT EXISTS user_locations (
  user_location_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  location_id INTEGER NOT NULL REFERENCES locations(location_id) ON DELETE CASCADE
);

-- 8. User Permissions Table (Action overrides)
CREATE TABLE IF NOT EXISTS user_permissions (
  user_permission_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  permission_id INTEGER NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE
);

-- 9. Consent Table
CREATE TABLE IF NOT EXISTS consent (
  id VARCHAR(255) PRIMARY KEY,
  subject_id VARCHAR(255) NOT NULL,
  consent_version VARCHAR(50) NOT NULL,
  consent_date VARCHAR(50) NOT NULL,
  document_url TEXT NOT NULL,
  verification_status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  withdrawn_at VARCHAR(255),
  withdrawn_by VARCHAR(255),
  submitted_by VARCHAR(255),
  submitted_date VARCHAR(255),
  consent_type VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. Samples Table
CREATE TABLE IF NOT EXISTS samples (
  id VARCHAR(255) PRIMARY KEY,
  subject_id VARCHAR(255) NOT NULL,
  gender VARCHAR(50) NOT NULL,
  age INTEGER NOT NULL,
  specimen_type VARCHAR(255) NOT NULL,
  specimen_type_id INTEGER,
  sample_volume REAL NOT NULL,
  container_type VARCHAR(255),
  container_count INTEGER,
  collection_date VARCHAR(50) NOT NULL,
  collection_time VARCHAR(50) NOT NULL,
  collection_datetime VARCHAR(255),
  lab_id INTEGER REFERENCES labs(id) ON DELETE SET NULL,
  collector_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  consent_id VARCHAR(255) REFERENCES consent(id) ON DELETE SET NULL,
  consent_status VARCHAR(50) DEFAULT 'Pending',
  barcode_status VARCHAR(50) DEFAULT 'Unassigned',
  status VARCHAR(50) NOT NULL DEFAULT 'Collected',
  consent_version VARCHAR(50),
  consent_template_id INTEGER,
  consent_template_ids TEXT,
  location VARCHAR(255),
  quality VARCHAR(255),
  diagnosis VARCHAR(255),
  qc_status VARCHAR(50) DEFAULT 'Pending',
  retrieval_status VARCHAR(50) DEFAULT 'Stored',
  ingestion_status VARCHAR(50) DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. Barcodes Table
CREATE TABLE IF NOT EXISTS barcodes (
  barcode_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sample_id VARCHAR(255) NOT NULL REFERENCES samples(id) ON DELETE CASCADE,
  barcode_value VARCHAR(255) NOT NULL UNIQUE,
  barcode_type VARCHAR(50) NOT NULL,
  generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  generated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  print_count INTEGER DEFAULT 0,
  status VARCHAR(50) DEFAULT 'Active',
  qr_code_base64 TEXT NOT NULL,
  code128_base64 TEXT NOT NULL
);

-- 12. Barcode Audit Table
CREATE TABLE IF NOT EXISTS barcode_audit (
  audit_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sample_id VARCHAR(255) NOT NULL REFERENCES samples(id) ON DELETE CASCADE,
  barcode_id INTEGER REFERENCES barcodes(barcode_id) ON DELETE SET NULL,
  action_type VARCHAR(255) NOT NULL,
  reason TEXT,
  performed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 13. Barcode History Table
CREATE TABLE IF NOT EXISTS barcode_history (
  history_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sample_id VARCHAR(255) NOT NULL REFERENCES samples(id) ON DELETE CASCADE,
  barcode_id INTEGER NOT NULL REFERENCES barcodes(barcode_id) ON DELETE CASCADE,
  barcode_value VARCHAR(255) NOT NULL,
  generated_at TIMESTAMP,
  generated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  print_count INTEGER,
  status VARCHAR(50),
  replaced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  replaced_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reason TEXT,
  qr_code_base64 TEXT,
  code128_base64 TEXT
);

-- 14. Accountability Activity Logs
CREATE TABLE IF NOT EXISTS user_activity_logs (
  activity_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  user_name VARCHAR(255),
  role VARCHAR(255),
  lab_name VARCHAR(255),
  module_name VARCHAR(255),
  action_type VARCHAR(50) NOT NULL,
  entity_type VARCHAR(100),
  entity_id VARCHAR(255),
  old_value TEXT,
  new_value TEXT,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ip_address VARCHAR(100)
);

-- 15. Consent Templates Table
CREATE TABLE IF NOT EXISTS consent_templates (
  template_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  consent_name VARCHAR(255) NOT NULL,
  consent_code VARCHAR(50) NOT NULL UNIQUE,
  consent_summary TEXT NOT NULL,
  consent_details TEXT NOT NULL,
  version VARCHAR(50) NOT NULL DEFAULT 'v1.0',
  effective_date VARCHAR(50),
  status VARCHAR(50) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 16. Shipments Table
CREATE TABLE IF NOT EXISTS shipments (
  id VARCHAR(255) PRIMARY KEY,
  origin_lab_id INTEGER REFERENCES labs(id) ON DELETE SET NULL,
  destination VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  shipped_at VARCHAR(255),
  received_at VARCHAR(255)
);

-- 17. Shipment Samples Table
CREATE TABLE IF NOT EXISTS shipment_samples (
  shipment_id VARCHAR(255) NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,
  sample_id VARCHAR(255) NOT NULL REFERENCES samples(id) ON DELETE CASCADE,
  PRIMARY KEY (shipment_id, sample_id)
);

-- 18. Research Requests Table
CREATE TABLE IF NOT EXISTS research_requests (
  id VARCHAR(255) PRIMARY KEY,
  researcher_name VARCHAR(255) NOT NULL,
  institution VARCHAR(255) NOT NULL,
  irb_code VARCHAR(50) NOT NULL,
  hypothesis TEXT NOT NULL,
  specimens TEXT NOT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 19. Studies Table
CREATE TABLE IF NOT EXISTS studies (
  id VARCHAR(255) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  irb_code VARCHAR(50) NOT NULL,
  investigator VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 20. Publications Table
CREATE TABLE IF NOT EXISTS publications (
  id VARCHAR(255) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  authors TEXT NOT NULL,
  journal VARCHAR(255) NOT NULL,
  doi VARCHAR(255),
  linked_study_id VARCHAR(255) REFERENCES studies(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 21. Specimen Types Table
CREATE TABLE IF NOT EXISTS specimen_types (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  specimen_code VARCHAR(50) NOT NULL UNIQUE,
  specimen_name VARCHAR(255) NOT NULL UNIQUE,
  category VARCHAR(100) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Database Performance Indexes for Neon PostgreSQL
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone_number);
CREATE INDEX IF NOT EXISTS idx_samples_subject ON samples(subject_id);
CREATE INDEX IF NOT EXISTS idx_samples_consent ON samples(consent_id);
CREATE INDEX IF NOT EXISTS idx_barcodes_value ON barcodes(barcode_value);
CREATE INDEX IF NOT EXISTS idx_barcodes_sample ON barcodes(sample_id);
CREATE INDEX IF NOT EXISTS idx_user_activity_logs_timestamp ON user_activity_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_locations_lab ON locations(lab_id);
CREATE INDEX IF NOT EXISTS idx_user_locations_user ON user_locations(user_id);
CREATE INDEX IF NOT EXISTS idx_user_permissions_user ON user_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON role_permissions(role_id);
