-- AURA BIOBANK PORTAL: BARCODE MANAGER SCHEMA MIGRATION
-- Adds support for parent/aliquot hierarchy, full status lifecycle, storage locations,
-- void & replacement tracking, print queue, and granular audit events.

-- 1. Extend barcodes table
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS parent_barcode_id INTEGER REFERENCES barcodes(barcode_id) ON DELETE SET NULL;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS parent_barcode_value VARCHAR(255);
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS aliquot_index INTEGER;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS volume REAL;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS volume_unit VARCHAR(50) DEFAULT 'mL';
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS storage_location VARCHAR(255);
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS replacement_of INTEGER REFERENCES barcodes(barcode_id) ON DELETE SET NULL;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS replacement_of_barcode_value VARCHAR(255);
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS replaced_by INTEGER REFERENCES barcodes(barcode_id) ON DELETE SET NULL;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS replaced_by_barcode_value VARCHAR(255);
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS void_reason TEXT;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS voided_at TIMESTAMP;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS voided_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS verified_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE barcodes ADD COLUMN IF NOT EXISTS barcode_format VARCHAR(50) DEFAULT 'CODE128_QR';

-- 2. Extend samples table
ALTER TABLE samples ADD COLUMN IF NOT EXISTS parent_sample_id VARCHAR(255) REFERENCES samples(id) ON DELETE SET NULL;
ALTER TABLE samples ADD COLUMN IF NOT EXISTS volume_unit VARCHAR(50) DEFAULT 'mL';
ALTER TABLE samples ADD COLUMN IF NOT EXISTS aliquot_count INTEGER DEFAULT 0;
ALTER TABLE samples ADD COLUMN IF NOT EXISTS barcode_value VARCHAR(255);

-- 3. Extend barcode_audit table
ALTER TABLE barcode_audit ADD COLUMN IF NOT EXISTS barcode_value VARCHAR(255);
ALTER TABLE barcode_audit ADD COLUMN IF NOT EXISTS old_value TEXT;
ALTER TABLE barcode_audit ADD COLUMN IF NOT EXISTS new_value TEXT;
ALTER TABLE barcode_audit ADD COLUMN IF NOT EXISTS related_entity_id VARCHAR(255);

-- 4. Create Print Queue table
CREATE TABLE IF NOT EXISTS print_queue (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  barcode_id INTEGER NOT NULL REFERENCES barcodes(barcode_id) ON DELETE CASCADE,
  sample_id VARCHAR(255) NOT NULL REFERENCES samples(id) ON DELETE CASCADE,
  copies INTEGER NOT NULL DEFAULT 1,
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  queued_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  queued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  printed_at TIMESTAMP,
  notes TEXT
);

-- 5. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_barcodes_parent_barcode_id ON barcodes(parent_barcode_id);
CREATE INDEX IF NOT EXISTS idx_barcodes_status ON barcodes(status);
CREATE INDEX IF NOT EXISTS idx_barcodes_replacement_of ON barcodes(replacement_of);
CREATE INDEX IF NOT EXISTS idx_barcodes_storage_location ON barcodes(storage_location);
CREATE INDEX IF NOT EXISTS idx_samples_parent_sample_id ON samples(parent_sample_id);
CREATE INDEX IF NOT EXISTS idx_samples_barcode_value ON samples(barcode_value);
CREATE INDEX IF NOT EXISTS idx_print_queue_status ON print_queue(status);
CREATE INDEX IF NOT EXISTS idx_print_queue_barcode_id ON print_queue(barcode_id);
CREATE INDEX IF NOT EXISTS idx_barcode_audit_barcode_value ON barcode_audit(barcode_value);
CREATE INDEX IF NOT EXISTS idx_barcode_audit_action_type ON barcode_audit(action_type);

-- 6. Insert Barcode Manager Action Permissions (Avoid Duplicates)
INSERT INTO permissions (permission_name, module_name) VALUES
  ('View Barcode', 'Barcode Manager'),
  ('Generate Barcode', 'Barcode Manager'),
  ('Print Barcode', 'Barcode Manager'),
  ('Reprint Barcode', 'Barcode Manager'),
  ('Scan Barcode', 'Barcode Manager'),
  ('Assign Storage', 'Barcode Manager'),
  ('Move Storage', 'Barcode Manager'),
  ('Void Barcode', 'Barcode Manager'),
  ('Replace Barcode', 'Barcode Manager'),
  ('Manage Barcodes', 'Barcode Manager'),
  ('Aliquot Specimen', 'Barcode Manager')
ON CONFLICT (permission_name) DO NOTHING;

-- 7. Deduplicate existing role_permissions before adding fresh mappings
DELETE FROM role_permissions WHERE role_permission_id NOT IN (
  SELECT MIN(role_permission_id) FROM role_permissions GROUP BY role_id, permission_id
);

-- 8. Map permissions to roles
-- Super Admin (role_id = 1): Full access
INSERT INTO role_permissions (role_id, permission_id)
SELECT 1, permission_id FROM permissions 
WHERE module_name = 'Barcode Manager'
ON CONFLICT DO NOTHING;

-- Lab Admin (role_id = 2): Full Barcode Manager access
INSERT INTO role_permissions (role_id, permission_id)
SELECT 2, permission_id FROM permissions 
WHERE module_name = 'Barcode Manager'
ON CONFLICT DO NOTHING;

-- Lab Technician (role_id = 3): Standard Barcode operational access
INSERT INTO role_permissions (role_id, permission_id)
SELECT 3, permission_id FROM permissions 
WHERE permission_name IN (
  'View Barcode', 'Generate Barcode', 'Print Barcode', 'Reprint Barcode',
  'Scan Barcode', 'Assign Storage', 'Move Storage', 'Aliquot Specimen', 'View Sample', 'Generate QR', 'Print QR', 'Reprint QR'
)
ON CONFLICT DO NOTHING;

-- Collection Staff (role_id = 4): View, Scan, Print
INSERT INTO role_permissions (role_id, permission_id)
SELECT 4, permission_id FROM permissions 
WHERE permission_name IN (
  'View Barcode', 'Scan Barcode', 'Print Barcode', 'View Sample', 'Print QR'
)
ON CONFLICT DO NOTHING;

-- Biobank Staff (role_id = 6): View, Scan, Print, Reprint, Storage
INSERT INTO role_permissions (role_id, permission_id)
SELECT 6, permission_id FROM permissions 
WHERE permission_name IN (
  'View Barcode', 'Scan Barcode', 'Print Barcode', 'Reprint Barcode',
  'Assign Storage', 'Move Storage', 'View Sample', 'Storage Assignment', 'Inventory Management'
)
ON CONFLICT DO NOTHING;
