import pg from 'pg';
import sqlite3 from 'sqlite3';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const isPostgres = !!process.env.DATABASE_URL;
let pgPool = null;
let sqliteDb = null;

if (isPostgres) {
  console.log("AURA DB: Connecting to PostgreSQL via pool...");
  pgPool = new pg.Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.DB_SSL === 'true' ? { rejectUnauthorized: false } : false
  });
} else {
  const dbDir = path.join(__dirname, 'data');
  if (!fs.existsSync(dbDir)) {
    fs.mkdirSync(dbDir, { recursive: true });
  }
  const dbPath = path.join(dbDir, 'biobank.db');
  console.log(`AURA DB: PostgreSQL not configured. Falling back to local SQLite database at: ${dbPath}`);
  sqliteDb = new sqlite3.Database(dbPath);
}

// Unified query runner
export function query(sql, params = []) {
  if (isPostgres) {
    // Translate SQLite style "?" placeholders to PostgreSQL style "$1, $2"
    let pgSql = sql;
    let count = 1;
    while (pgSql.includes('?')) {
      pgSql = pgSql.replace('?', `$${count}`);
      count++;
    }
    return pgPool.query(pgSql, params)
      .then(res => ({
        rows: res.rows,
        rowCount: res.rowCount
      }));
  } else {
    return new Promise((resolve, reject) => {
      const cleanSql = sql.trim();
      const isSelect = cleanSql.toUpperCase().startsWith('SELECT');

      if (isSelect) {
        sqliteDb.all(sql, params, (err, rows) => {
          if (err) return reject(err);
          resolve({ rows, rowCount: rows.length });
        });
      } else {
        sqliteDb.run(sql, params, function(err) {
          if (err) return reject(err);
          resolve({
            rows: [],
            rowCount: this.changes,
            lastID: this.lastID
          });
        });
      }
    });
  }
}

// Database schema initialization
export async function initDb() {
  const createTablesSql = [
    // 1. Labs Table
    `CREATE TABLE IF NOT EXISTS labs (
      id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      name TEXT NOT NULL UNIQUE,
      location_address TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'Active',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    // 2. Roles Table
    `CREATE TABLE IF NOT EXISTS roles (
      role_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      role_name TEXT NOT NULL UNIQUE,
      description TEXT
    )`,

    // 3. Permissions Table
    `CREATE TABLE IF NOT EXISTS permissions (
      permission_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      permission_name TEXT NOT NULL UNIQUE,
      module_name TEXT NOT NULL
    )`,

    // 4. Role Permissions Table
    `CREATE TABLE IF NOT EXISTS role_permissions (
      role_permission_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      role_id INTEGER NOT NULL,
      permission_id INTEGER NOT NULL
    )`,

    // 5. Locations Table
    `CREATE TABLE IF NOT EXISTS locations (
      location_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      lab_id INTEGER,
      location_name TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'Active'
    )`,

    // 6. User Locations Table
    `CREATE TABLE IF NOT EXISTS user_locations (
      user_location_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      user_id INTEGER NOT NULL,
      location_id INTEGER NOT NULL
    )`,

    // 7. User Custom Permissions Table (Action-based overrides)
    `CREATE TABLE IF NOT EXISTS user_permissions (
      user_permission_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      user_id INTEGER NOT NULL,
      permission_id INTEGER NOT NULL
    )`,

    // 8. Users Table with complete Accountability fields
    `CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      name TEXT NOT NULL,
      full_name TEXT,
      phone_number TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      employee_id TEXT,
      designation TEXT,
      role_id INTEGER,
      lab_id INTEGER,
      status TEXT NOT NULL DEFAULT 'Active',
      password TEXT,
      created_by TEXT,
      created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      modified_by TEXT,
      modified_date TEXT,
      activated_by TEXT,
      activated_date TEXT,
      deactivated_by TEXT,
      deactivated_date TEXT,
      suspended_by TEXT,
      suspended_date TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    // 9. Consent Table
    `CREATE TABLE IF NOT EXISTS consent (
      id TEXT PRIMARY KEY,
      subject_id TEXT NOT NULL,
      consent_version TEXT NOT NULL,
      consent_date TEXT NOT NULL,
      document_url TEXT NOT NULL,
      verification_status TEXT NOT NULL DEFAULT 'Pending',
      withdrawn_at TEXT,
      withdrawn_by TEXT,
      submitted_by TEXT,
      submitted_date TEXT,
      consent_type TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    // 10. Samples Table
    `CREATE TABLE IF NOT EXISTS samples (
      id TEXT PRIMARY KEY,
      subject_id TEXT NOT NULL,
      gender TEXT NOT NULL,
      age INTEGER NOT NULL,
      specimen_type TEXT NOT NULL,
      sample_volume REAL NOT NULL,
      container_type TEXT,
      container_count INTEGER,
      collection_date TEXT NOT NULL,
      collection_time TEXT NOT NULL,
      collection_datetime TEXT,
      lab_id INTEGER,
      collector_id INTEGER,
      consent_id TEXT,
      consent_status TEXT DEFAULT 'Pending',
      barcode_status TEXT DEFAULT 'Unassigned',
      status TEXT NOT NULL DEFAULT 'Collected',
      consent_version TEXT,
      consent_template_id INTEGER,
      consent_template_ids TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    // 11. Barcodes Table
    `CREATE TABLE IF NOT EXISTS barcodes (
      barcode_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      sample_id TEXT NOT NULL,
      barcode_value TEXT NOT NULL UNIQUE,
      barcode_type TEXT NOT NULL,
      generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      generated_by INTEGER,
      print_count INTEGER DEFAULT 0,
      status TEXT DEFAULT 'Active',
      qr_code_base64 TEXT NOT NULL,
      code128_base64 TEXT NOT NULL
    )`,

    // 12. Barcode Audit Table
    `CREATE TABLE IF NOT EXISTS barcode_audit (
      audit_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      sample_id TEXT NOT NULL,
      barcode_id INTEGER,
      action_type TEXT NOT NULL,
      reason TEXT,
      performed_by INTEGER,
      action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    // 13. Barcode History Table
    `CREATE TABLE IF NOT EXISTS barcode_history (
      history_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      sample_id TEXT NOT NULL,
      barcode_id INTEGER NOT NULL,
      barcode_value TEXT NOT NULL,
      generated_at TIMESTAMP,
      generated_by INTEGER,
      print_count INTEGER,
      status TEXT,
      replaced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      replaced_by INTEGER,
      reason TEXT,
      qr_code_base64 TEXT,
      code128_base64
    )`,

    // 14. Accountability Activity Logs (Replaces audit_logs)
    `CREATE TABLE IF NOT EXISTS user_activity_logs (
      activity_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      user_id INTEGER,
      user_name TEXT,
      role TEXT,
      lab_name TEXT,
      module_name TEXT,
      action_type TEXT NOT NULL,
      entity_type TEXT,
      entity_id TEXT,
      old_value TEXT,
      new_value TEXT,
      timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      ip_address TEXT
    )`,

    // 15. Consent Templates Table
    `CREATE TABLE IF NOT EXISTS consent_templates (
      template_id INTEGER PRIMARY KEY ${isPostgres ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTOINCREMENT'},
      consent_name TEXT NOT NULL,
      consent_code TEXT NOT NULL UNIQUE,
      consent_summary TEXT NOT NULL,
      consent_details TEXT NOT NULL,
      version TEXT NOT NULL DEFAULT 'v1.0',
      effective_date TEXT,
      status TEXT NOT NULL DEFAULT 'Active',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    // 16. Shipments Table
    `CREATE TABLE IF NOT EXISTS shipments (
      id TEXT PRIMARY KEY,
      origin_lab_id INTEGER,
      destination TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'Pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      shipped_at TEXT,
      received_at TEXT
    )`,

    // 17. Shipment Samples Table
    `CREATE TABLE IF NOT EXISTS shipment_samples (
      shipment_id TEXT NOT NULL,
      sample_id TEXT NOT NULL,
      PRIMARY KEY (shipment_id, sample_id)
    )`,

    // 18. Research Requests Table
    `CREATE TABLE IF NOT EXISTS research_requests (
      id TEXT PRIMARY KEY,
      researcher_name TEXT NOT NULL,
      institution TEXT NOT NULL,
      irb_code TEXT NOT NULL,
      hypothesis TEXT NOT NULL,
      specimens TEXT NOT NULL,
      status TEXT DEFAULT 'Pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    // 19. Studies Table
    `CREATE TABLE IF NOT EXISTS studies (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      irb_code TEXT NOT NULL,
      investigator TEXT NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    // 20. Publications Table
    `CREATE TABLE IF NOT EXISTS publications (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      authors TEXT NOT NULL,
      journal TEXT NOT NULL,
      doi TEXT,
      linked_study_id TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`
  ];

  for (const sql of createTablesSql) {
    await query(sql);
  }

  // Safe migration check for existing schemas
  try {
    await query("ALTER TABLE samples ADD COLUMN consent_version TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN consent_template_id INTEGER");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN location TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN quality TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN diagnosis TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN qc_status TEXT DEFAULT 'Pending'");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN retrieval_status TEXT DEFAULT 'Stored'");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN ingestion_status TEXT DEFAULT 'Pending'");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN consent_template_ids TEXT");
  } catch (e) {}
  try {
    await query("UPDATE samples SET consent_template_ids = '[' || consent_template_id || ']' WHERE consent_template_ids IS NULL AND consent_template_id IS NOT NULL");
  } catch (e) {}
  try {
    await query("ALTER TABLE users ADD COLUMN password TEXT");
  } catch (e) {}
  try {
    await query("UPDATE users SET password = 'lims2026' WHERE password IS NULL");
  } catch (e) {}
  try {
    await query("ALTER TABLE consent ADD COLUMN withdrawn_at TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE consent ADD COLUMN withdrawn_by TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE consent ADD COLUMN submitted_by TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE consent ADD COLUMN submitted_date TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE consent ADD COLUMN consent_type TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN container_type TEXT");
  } catch (e) {}
  try {
    await query("ALTER TABLE samples ADD COLUMN container_count INTEGER");
  } catch (e) {}

  console.log("AURA DB: Database tables initialized.");

  // Seeding default laboratories
  const labsCheck = await query("SELECT COUNT(*) as count FROM labs");
  if (labsCheck.rows[0].count === 0) {
    console.log("AURA DB: Seeding default laboratories...");
    await query("INSERT INTO labs (name, location_address, status) VALUES (?, ?, ?)", [
      "Metropolis Lab Boston", "75 Binney St, Boston, MA 02142", "Active"
    ]);
    await query("INSERT INTO labs (name, location_address, status) VALUES (?, ?, ?)", [
      "ABC Diagnostics", "100 Broadway, Cambridge, MA 02139", "Active"
    ]);
    await query("INSERT INTO labs (name, location_address, status) VALUES (?, ?, ?)", [
      "XYZ Research Center", "500 Tech Sq, Cambridge, MA 02139", "Active"
    ]);
  }

  // Seeding default locations
  const locCheck = await query("SELECT COUNT(*) as count FROM locations");
  if (locCheck.rows[0].count === 0) {
    console.log("AURA DB: Seeding default locations...");
    await query("INSERT INTO locations (lab_id, location_name) VALUES (1, 'Collection Center A')");
    await query("INSERT INTO locations (lab_id, location_name) VALUES (1, 'Collection Center B')");
    await query("INSERT INTO locations (lab_id, location_name) VALUES (2, 'Collection Center B')");
    await query("INSERT INTO locations (lab_id, location_name) VALUES (2, 'Central Biobank')");
    await query("INSERT INTO locations (lab_id, location_name) VALUES (3, 'Central Biobank')");
  }

  // Seeding default roles
  const rolesCheck = await query("SELECT COUNT(*) as count FROM roles");
  if (rolesCheck.rows[0].count === 0) {
    console.log("AURA DB: Seeding default roles...");
    const defaultRoles = [
      { id: 1, name: "Super Admin", desc: "Full System Access" },
      { id: 2, name: "Lab Admin", desc: "Manage laboratory operations, users, and shipments" },
      { id: 3, name: "Lab Technician", desc: "Process specimens, verify consent, and generate/print labels" },
      { id: 4, name: "Collection Staff", desc: "Register specimens and track their own collections" },
      { id: 5, name: "Courier Staff", desc: "Dispatch and transport specimens" },
      { id: 6, name: "Biobank Staff", desc: "Receive, QC, store, and manage specimens" },
      { id: 7, name: "Research Staff", desc: "Query approved inventory and build research exports" }
    ];
    for (const r of defaultRoles) {
      await query("INSERT INTO roles (role_id, role_name, description) VALUES (?, ?, ?)", [
        r.id, r.name, r.desc
      ]);
    }
  }

  // Seeding default action-based permissions
  const permCheck = await query("SELECT COUNT(*) as count FROM permissions");
  if (permCheck.rows[0].count === 0) {
    console.log("AURA DB: Seeding action-based permissions...");
    const list = [
      // Sample Management
      { name: "Create Sample", module: "Sample Management" },
      { name: "Edit Sample", module: "Sample Management" },
      { name: "View Sample", module: "Sample Management" },
      { name: "Delete Sample", module: "Sample Management" },
      // Consent Management
      { name: "Create Consent", module: "Consent Management" },
      { name: "Verify Consent", module: "Consent Management" },
      { name: "Reject Consent", module: "Consent Management" },
      { name: "View Consent", module: "Consent Management" },
      // QR Management
      { name: "Generate QR", module: "QR Management" },
      { name: "Print QR", module: "QR Management" },
      { name: "Reprint QR", module: "QR Management" },
      // Shipment Management
      { name: "Create Shipment", module: "Shipment Management" },
      { name: "Edit Shipment", module: "Shipment Management" },
      { name: "Dispatch Shipment", module: "Shipment Management" },
      { name: "Receive Shipment", module: "Shipment Management" },
      // User Management
      { name: "Create User", module: "User Management" },
      { name: "Edit User", module: "User Management" },
      { name: "Activate User", module: "User Management" },
      { name: "Deactivate User", module: "User Management" },
      { name: "View Users", module: "User Management" },
      // Reports
      { name: "View Reports", module: "Reports" },
      { name: "Export Reports", module: "Reports" },
      // Administration
      { name: "View Audit Logs", module: "Administration" },
      { name: "Manage Roles", module: "Administration" },
      { name: "Manage Permissions", module: "Administration" },
      // Biobank Staff Operations
      { name: "Receive Samples", module: "Biobank Management" },
      { name: "QC Processing", module: "Biobank Management" },
      { name: "Storage Assignment", module: "Biobank Management" },
      { name: "Inventory Management", module: "Biobank Management" },
      // Research Staff Operations
      { name: "View Approved Inventory", module: "Research Management" }
    ];
    for (const p of list) {
      await query("INSERT INTO permissions (permission_name, module_name) VALUES (?, ?)", [
        p.name, p.module
      ]);
    }
  }

  // Seeding role_permissions mappings based on default matrix
  const rpCheck = await query("SELECT COUNT(*) as count FROM role_permissions");
  if (rpCheck.rows[0].count === 0) {
    console.log("AURA DB: Seeding role permissions default matrix...");
    const permsRows = (await query("SELECT * FROM permissions")).rows;
    const getPermId = (name) => permsRows.find(p => p.permission_name === name)?.permission_id;

    // Helper to batch map permissions to role_id
    const mapRolePerms = async (roleId, permNames) => {
      for (const name of permNames) {
        const pId = getPermId(name);
        if (pId) {
          await query("INSERT INTO role_permissions (role_id, permission_id) VALUES (?, ?)", [
            roleId, pId
          ]);
        }
      }
    };

    // LAB ADMIN MAPPINGS
    await mapRolePerms(2, [
      "Create User", "Edit User", "Activate User", "Deactivate User", "View Users",
      "Create Sample", "Edit Sample", "View Sample", "Delete Sample",
      "Create Consent", "Verify Consent", "Reject Consent", "View Consent",
      "Generate QR", "Print QR", "Reprint QR",
      "Create Shipment", "Edit Shipment", "Dispatch Shipment", "Receive Shipment",
      "View Reports", "Export Reports", "View Audit Logs"
    ]);

    // LAB TECHNICIAN MAPPINGS
    await mapRolePerms(3, [
      "Create Sample", "Edit Sample", "View Sample",
      "Generate QR", "Print QR"
    ]);

    // COLLECTION STAFF MAPPINGS
    await mapRolePerms(4, [
      "Create Sample", "View Sample"
    ]);

    // BIOBANK STAFF MAPPINGS
    await mapRolePerms(6, [
      "Receive Shipment", "Receive Samples", "QC Processing", "Storage Assignment", "Inventory Management"
    ]);

    // RESEARCH STAFF MAPPINGS
    await mapRolePerms(7, [
      "View Approved Inventory", "View Reports"
    ]);
  }

  // Seeding Default Super Admin User
  const usersCheck = await query("SELECT COUNT(*) as count FROM users");
  if (usersCheck.rows[0].count === 0) {
    console.log("AURA DB: Seeding default Super Admin user profile...");
    await query(`
      INSERT INTO users (
        id, name, full_name, phone_number, email, employee_id, designation, 
        role_id, lab_id, status, password, created_by, created_date
      ) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
    `, [
      "Super Admin", "Super Admin", "5550000000", "superadmin@aura.com", "EMP-001", "Chief Administrator",
      1, null, "Active", "lims2026", "System"
    ]);

    await query(`
      INSERT INTO users (
        id, name, full_name, phone_number, email, employee_id, designation, 
        role_id, lab_id, status, password, created_by, created_date
      ) VALUES (2, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
    `, [
      "Puja Pramanik", "Puja Pramanik", "7595916852", "pujapramanik12451@gmail.com", "EMP-002", "Lead Administrator",
      1, null, "Active", "lims2026", "System"
    ]);



    // Super Admin locations setup
    await query("INSERT INTO user_locations (user_id, location_id) VALUES (1, 1)");
    await query("INSERT INTO user_locations (user_id, location_id) VALUES (1, 2)");
    await query("INSERT INTO user_locations (user_id, location_id) VALUES (1, 3)");

    await query("INSERT INTO user_locations (user_id, location_id) VALUES (2, 1)");
    await query("INSERT INTO user_locations (user_id, location_id) VALUES (2, 2)");
    await query("INSERT INTO user_locations (user_id, location_id) VALUES (2, 3)");
  }

  // Seeding default active consent templates
  const templatesCheck = await query("SELECT COUNT(*) as count FROM consent_templates");
  if (templatesCheck.rows[0].count === 0) {
    console.log("AURA DB: Seeding default active consent templates...");
    const defaultTemplates = [
      {
        name: "General Biobank Consent",
        code: "GBC",
        summary: JSON.stringify({
          purpose: "Authorizes storage of biological samples in the AURA Biobank.",
          allows: [
            "Sample storage",
            "Future approved research use",
            "De-identified data usage"
          ],
          restrictions: [
            "Personal identity will remain protected."
          ]
        }),
        details: "This document establishes consent for the collection and storage of biological materials (specimens) and associated health data in the AURA Biobank. The biospecimens will be used for future biomedical research aiming to understand health and disease. By signing this document, the participant acknowledges that participation is voluntary, samples will be coded to protect privacy, and they will receive no direct financial benefits. The samples may be stored indefinitely.",
        version: "v1.0",
        effective_date: "2026-06-02",
        status: "Active"
      },
      {
        name: "Future Research Consent",
        code: "FRC",
        summary: JSON.stringify({
          purpose: "Allows samples to be used in future unspecified biomedical research projects.",
          allows: [
            "Unspecified future studies",
            "Sharing with external researchers",
            "Secondary analysis"
          ],
          restrictions: [
            "Subject to IRB approval."
          ]
        }),
        details: "This consent authorizes the biobank to distribute collected biospecimens and de-identified clinical data to qualified research investigators worldwide. These investigations may include genetic, biochemical, or immunological studies. The biobank ensures that all sharing is governed by strict material transfer agreements, and all studies are subject to oversight and approval by an Institutional Review Board (IRB) or equivalent ethical review body.",
        version: "v1.0",
        effective_date: "2026-06-02",
        status: "Active"
      },
      {
        name: "Re-contact Consent",
        code: "RCC",
        summary: JSON.stringify({
          purpose: "Permission to contact the participant for follow-up studies or clinical updates.",
          allows: [
            "Re-contacting via phone/email",
            "Sharing genetic findings of high clinical relevance"
          ],
          restrictions: [
            "No obligation to participate in future studies."
          ]
        }),
        details: "By opting into the re-contact consent, you allow Aura Biobank personnel or authorized investigators to contact you in the future. Future contact may be initiated to collect follow-up health information, request updates, or invite you to participate in specific clinical trials or studies related to your sample. Additionally, if research reveals actionable genetic findings of high medical significance to your health, this consent enables the biobank to offer this information back to you.",
        version: "v1.0",
        effective_date: "2026-06-02",
        status: "Active"
      },
      {
        name: "Fluid Processing & Aliquoting Authorization",
        code: "FPA",
        summary: JSON.stringify({
          purpose: "Authorizes processing and aliquoting of fluid biospecimens (e.g., blood, plasma).",
          allows: [
            "Centrifugation",
            "Aliquot separation",
            "Sub-zero storage"
          ],
          restrictions: [
            "Minimal processing deviation."
          ]
        }),
        details: "This authorization covers the technical processing, centrifugation, fraction separation (serum, plasma, buffy coat), aliquoting, and cryopreservation of liquid biospecimens (including whole blood, saliva, and urine). The processing is conducted under ISO standard operating procedures to maintain sample integrity and stability. Aliquoting allows multiple future studies to utilize the sample without repeated freeze-thaw cycles.",
        version: "v1.0",
        effective_date: "2026-06-02",
        status: "Active"
      },
      {
        name: "Proteomic & Biomarker Analysis Consent",
        code: "PBA",
        summary: JSON.stringify({
          purpose: "Allows proteomic profiling and discovery of novel biological markers.",
          allows: [
            "Mass spectrometry",
            "Protein expression mapping",
            "Target marker validation"
          ],
          restrictions: [
            "No genetic sequencing permitted under this specific scope."
          ]
        }),
        details: "This consent authorizes research focusing on the analysis of proteins, peptides, and other small-molecule biomarkers within the submitted biospecimens. Techniques applied may include mass spectrometry, enzyme-linked immunosorbent assays (ELISA), and high-throughput proteomic arrays. This research aims to discover diagnostic or prognostic indicators of disease. This consent is restricted to protein-level analyses and does not cover whole-genome or exome DNA sequencing.",
        version: "v1.0",
        effective_date: "2026-06-02",
        status: "Active"
      },
      {
        name: "Long-Term Cryopreservation Authorization",
        code: "LTC",
        summary: JSON.stringify({
          purpose: "Allows long-term storage of biological samples in cryogenic freezers.",
          allows: [
            "Long-term preservation",
            "Future retrieval for approved studies"
          ],
          restrictions: [
            "Research use only."
          ]
        }),
        details: "This authorization enables the biobank to store the provided biological specimens in vapor-phase liquid nitrogen or ultra-low temperature mechanical freezers (-80°C or colder) for long-term preservation. The storage is planned for a standard duration of 25 years or until the sample is fully depleted in approved research. This long-term cryopreservation is strictly reserved for scientific and medical research purposes.",
        version: "v1.0",
        effective_date: "2026-06-02",
        status: "Active"
      }
    ];

    for (const t of defaultTemplates) {
      await query(`
        INSERT INTO consent_templates (consent_name, consent_code, consent_summary, consent_details, version, effective_date, status)
        VALUES (?, ?, ?, ?, ?, ?, ?)
      `, [t.name, t.code, t.summary, t.details, t.version, t.effective_date, t.status]);
    }
  }

  // Seeding initial samples & barcodes - REMOVED DUMMY SEEDS
  const samplesCheck = await query("SELECT COUNT(*) as count FROM samples");
  if (samplesCheck.rows[0].count === 0) {
    console.log("AURA DB: Initial samples table is clean. Waiting for user registration.");
  }

  // Seeding research studies - REMOVED DUMMY SEEDS
  const studiesCheck = await query("SELECT COUNT(*) as count FROM studies");
  if (studiesCheck.rows[0].count === 0) {
    console.log("AURA DB: Studies table is clean.");
  }

  // Seeding publications - REMOVED DUMMY SEEDS
  const pubCheck = await query("SELECT COUNT(*) as count FROM publications");
  if (pubCheck.rows[0].count === 0) {
    console.log("AURA DB: Publications table is clean.");
  }

  // Seeding research requests - REMOVED DUMMY SEEDS
  const requestsCheck = await query("SELECT COUNT(*) as count FROM research_requests");
  if (requestsCheck.rows[0].count === 0) {
    console.log("AURA DB: Research requests table is clean.");
  }

  console.log("AURA DB: Default dataset seeded successfully.");
}
